routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', 'Front\HomeController@homepage');

Route::group(['namespace' => 'Back'], function () {
    Route::get('/login', 'HomeController@login')->name('login')->middleware('guest:admin');
    Route::group(['namespace' => 'Auth'], function () {
        Route::post('login-action', 'LoginController@login')->name('login_action')->middleware('guest:admin');
        Route::get('logout', 'LoginController@logout')->name('logout');
    });

    Route::group(['middleware' => 'auth:admin,SA,RT,LT'], function () {
        Route::get('/dashboard', 'DashboardController@index')->name('index');
        Route::resource('profile', 'ProfileController');
        Route::get('reset-password', 'PasswordResetController@showReset')->name('back.show_reset');
        Route::post('reset-password-action', 'PasswordResetController@resetAction')->name('back.reset_action');
    });

    Route::group(['middleware' => 'auth:admin,SA'], function () {
        Route::resource('admin', 'AdminController');
        Route::get('update-status/{id}', 'AdminController@updateStatus')->name('admin.update_status');
        Route::resource('settings', 'SettingController');
    });

    Route::group(['middleware' => 'auth:admin,SA,RT',], function () {
        Route::resource('patient', 'PatientController', ['excepts' => 'create']);
        Route::get('patient/create/{id?}', ['as' => 'patient.create', 'uses' => 'PatientController@create']);
        Route::get('patient/details/{id}', ['as' => 'patient.details', 'uses' => 'PatientController@patientDetails']);
        Route::get('view-generate-invoice', 'InvoiceController@viewToGenerateInvoice')->name('back.view_to_generate_invoice');
        Route::get('generate-invoice/{id}', 'InvoiceController@generate')->name('back.generate_invoice');
        Route::get('invoice-paid/{id}','InvoiceController@paid')->name('back.invoice_paid');

    });

    Route::group(['middleware' => 'auth:admin,SA,LT',], function () {
        Route::resource('test', 'TestController');
        Route::resource('test-list', 'TestListController');
        Route::get('view-sample', 'SampleController@viewSample')->name('back.view_sample');
        Route::get('collect-sample/{id}', 'SampleController@collect')->name('back.collect_sample');
        Route::post('collect-sample', 'SampleController@collectAction')->name('back.collect_action');
        Route::get('edit-sample/{id}', 'SampleController@editSample')->name('back.edit_sample');
        Route::post('update-sample', 'SampleController@updateSample')->name('back.update_sample');
        Route::get('view-details/{id}', 'SampleController@viewDetails')->name('back.view_details');
        Route::resource('report', 'ReportController', ['excepts' => 'create']);
        Route::get('report/create/{id}', ['as' => 'report.create', 'uses' => 'ReportController@create']);
        Route::get('report/generate/{id}','ReportController@generate')->name('back.report_generate');
    });
});

app/Models/Patient.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Patient extends Model
{
    protected $table = 'patients';
    protected $fillable = ['first_name', 'middle_name', 'last_name', 'age', 'email', 'gender', 'address', 'phone', 'consultant', 'patient_category', 'his_no'];

    public function samples()
    {
        return $this->hasMany(Sample::class);
    }

    public function testLists()
    {
        return $this->belongsToMany(TestList::class, 'samples');
    }

    public function sampleType()
    {
        return $this->hasMany(SampleType::class);
    }

    public function getFullNameAttribute()
    {
        return ucwords($this->first_name . ' ' . $this->middle_name . ' ' . $this->last_name);
    }

    public function reports()
    {
        return $this->hasMany(Report::class, 'patient_id');
    }

    public function invoice()
    {
        return $this->hasOne(Invoice::class);
    }

}

app/Models/Report.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Report extends Model
{
    protected $table = 'reports';
    protected $fillable = ['patient_id', 'test_list_id', 'test_list_value', 'remarks'];

    public function patient()
    {
        return $this->belongsTo(Patient::class);
    }

    public function testLists()
    {
        return $this->belongsTo(TestList::class, 'test_list_id');
    }


}

app/Http/Controllers/Back/ReportController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Admin;
use App\Models\Patient;
use App\Models\Report;
use App\Models\Sample;
use App\Models\SampleType;
use App\Models\Setting;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ReportController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $reports = Report::query();
        $search = \request()->search;
        if (\request()->has('search') && \request()->search != null)
            $reports->whereHas('patient', function ($q) use ($search) {
                $q->where('first_name', 'like', '%' . $search . '%')->orWhere('phone', 'like', '%' . $search . '%');
            });
        $reports = $reports->where('status', null)->latest()->paginate(200);
        return view('pages.report.view_to_generate_report', compact('reports'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $id = \request()->id;
        $patient = Patient::findOrFail($id);
        $sample_types = \Opis\Closure\unserialize(SampleType::where('patient_id', $patient->id)->latest()->value('type'));
        $samples = Sample::where('patient_id', $patient->id)->where('status', '!=', 'done')->latest()->get();
//        dd($samples);
        return view('pages.report.input_test_results', compact('patient', 'sample_types', 'samples'));
    }

    /**
     * Store a newly created resource in storage.
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        foreach ($request->input('reports') as $key => $value) {
            $report = new Report();
            $report->patient_id = $request->input('patient_id');
            $report->test_list_id = $key;
            $report->test_list_value = $value;
            $report->save();
        }

        $patient = Patient::findOrFail($request->input('patient_id'));
        $patient->status = 'done';
        $patient->save();

        $samples = Sample::where('patient_id', $request->input('patient_id'))->where('status', '!=', 'done')->latest()->get();
        foreach ($samples as $sample) {
            $sample->status = 'done';
            $sample->save();
        }
        $sample_type = SampleType::where('patient_id', $patient->id)->where('status', 'collected')->first();
        $sample_type->status = 'done';
        $sample_type->save();
        return redirect()->route('report.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $patient = Patient::findOrFail($id);
        $reports = Report::where('patient_id', $id)->where('status', null)->get();
        $admin = Auth::guard('admin')->user();
        $date_time = Carbon::now('+5:45');
        $settings = Setting::first();
        return view('pages.report.view_report', compact('patient', 'reports', 'admin', 'date_time', 'settings'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $report = Report::findOrFail($id);
        $patient = Patient::where('id', $report->patient_id)->first();
        $sample_types = \Opis\Closure\unserialize(SampleType::where('patient_id', $patient->id)->latest()->value('type'));
        $samples = Sample::where('patient_id', $report->patient_id)->latest()->get();
        return view('pages.report.edit_test_results', compact('patient', 'report', 'sample_types', 'samples'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $patient = Patient::where('id', $request->input('patient_id'))->first();
        $reports = Report::where('patient_id', $request->input('patient_id'))->where('status', null)->get();
        $test_list_ids = [];
        $test_list_values = [];
        foreach ($request->input('reports') as $key => $value) {
            array_push($test_list_ids, $key);
            array_push($test_list_values, $value);
        }
        $i = 0;
        foreach ($reports as $report) {
            for ($j = $i; $j <= count($reports);) {
                $report->patient_id = $patient->id;
                $report->test_list_id = $test_list_ids[$i];
                $report->test_list_value = $test_list_values[$i];
                $report->save();
                break;
            }
            $i++;
        }
        return redirect()->back()->with('success', 'Test results updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */

    public function generate()
    {
        $reports = Report::where('patient_id', \request()->id)->where('status', null)->get();
        foreach ($reports as $r) {
            $r->status = 'generated';
            $r->save();
        }
        return redirect()->route('report.index');
    }

    public function destroy($id)
    {
        //
    }
}

resources/views/pages/report/edit_test_results.blade.php
@extends('master')
@section('content')
    <!-- Begin Page Content -->
    <div class="container">
        @include('messages.message')
        <div class="card">
            <div class="card-header text-primary text-center">
                <h4 class="mb-0">Edit Patient's Test Result/s</h4>
            </div>
            <div class="card-body">
                <form action="{{route('report.update',$report->id)}}" method="post">
                    @method('PUT')
                    @csrf
                    <input type="hidden" value="{{$patient->id}}" name="patient_id">
                    <div class="row col-md-12">
                        <div class="form-group col-md-4">
                            <label for="">Full Name</label>
                            <input type="text" class="form-control" name="patient_name"
                                   value="{{$patient->getFullNameAttribute()}}" readonly>
                        </div>
                        <div class="form-group col-md-4">
                            <label for="">Age</label>
                            <input type="text" class="form-control" name="age" value="{{$patient->age}} yrs" readonly>
                        </div>
                        <div class="from-group col-md-4">
                            <label for="">Gender</label>
                            <input type="text" class="form-control" name="gender" value="{{$patient->gender}}" readonly>
                        </div>
                    </div>
                    <div class="row col-md-12">
                        <div class="form-group col-md-6">
                            <label for=""><b>Sample Types</b></label>
                            <ul>
                                @foreach($sample_types as $st)
                                    <li>{{$st}}</li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                    <div class="row col-md-12">
                        <div class="form-group col-md-12">
                            <label for=""><b>Input Test Results Value</b></label>
                            <table class="">
                                <thead>
                                <tr>
                                    <th>Tests</th>
                                    <th>Value</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($patient->reports as $pr)
                                    @if($pr->status != 'generated')
                                        <tr>
                                            <td style="padding: 15px 15px 15px 10px"
                                                class="mb-4">{{$pr->testLists->name}}</td>
                                            @if($pr->testLists->subCategories != null)
                                                @foreach($pr->testLists->subCategories as $sc)
                                                    <td style="padding-right: 5px">
                                                        {{$sc->name}}
                                                        <input type="text" class="form-control"
                                                               name="reports[{{$sc->id}}]"
                                                               value="{{$sc->test_list_value}}" required>
                                                    </td>
                                                @endforeach
                                            @endif
                                            @if(count($pr->testLists->subCategories) == null)
                                                <td style="padding: 0">
                                                    <input type="text" class="form-control"
                                                           name="reports[{{$pr->testLists->id}}]"
                                                           value="{{$pr->test_list_value}}" required>
                                                </td>
                                            @endif
                                        </tr>
                                    @endif
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="mt-2 mb-4 text-center">
                        <a href="{{route('report.index')}}" class="btn btn-primary mr-2">Back</a>
                        <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
@stop

resources/views/pages/report/input_test_results.blade.php
@extends('master')
@section('content')

    <!-- Begin Page Content -->
    <div class="container">
        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between">
            <h1 class="h3 mb-0 text-gray-800">Input Patient's Test Result/s</h1>
        </div>
        <hr style="margin-top: 5px!important;" class="mb-4">
        <div class="">
            <form action="{{route('report.store')}}" method="post">
                @csrf
                <input type="hidden" value="{{$patient->id}}" name="patient_id">
                <div class="row col-md-12">
                    <div class="form-group col-md-4">
                        <label for="">Full Name</label>
                        <input type="text" class="form-control" name="patient_name"
                               value="{{$patient->getFullNameAttribute()}}" readonly>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="">Age</label>
                        <input type="text" class="form-control" name="age" value="{{$patient->age}} yrs" readonly>
                    </div>
                    <div class="from-group col-md-4">
                        <label for="">Gender</label>
                        <input type="text" class="form-control" name="gender" value="{{$patient->gender}}" readonly>
                    </div>
                </div>
                <div class="row col-md-12">
                    <div class="form-group col-md-6">
                        <label for=""><b>Sample Types</b></label>
                        <ul>
                            @foreach($sample_types as $st)
                                <li>{{$st}}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
                <div class="row col-md-12">
                    <div class="form-group col-md-12">
                        <label for=""><b>Input Test Results Value</b></label>
                        <table class="">
                            <thead>
                            <tr>
                                <th>Tests</th>
                                <th>Value</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($samples as $s)
                                <tr>
                                    <td style="padding: 15px 15px 15px 10px" class="mb-4">{{$s->testLists->name}}</td>
                                @if($s->testLists->subCategories)
                                    @foreach($s->testLists->subCategories as $sc)
                                            <td style="padding-right: 5px">
                                                {{$sc->name}}
                                                <input type="text" class="form-control" name="reports[{{$sc->id}}]"
                                                       required>
                                            </td>
                                        @endforeach
                                    @endif
                                @if(count($s->testLists->subCategories) == null)
                                        <td style="padding: 0">
                                            <input type="text" class="form-control" name="reports[{{$s->testLists->id}}]" required>
                                        </td>
                                    @endif
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="mt-4 text-center mb-4">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
    <!-- /.container-fluid -->
@stop

resources/views/pages/report/view_report.blade.php
@extends('master')
@section('content')

    <div class="print text-center d-print-none">
        <a href="{{route('report.index')}}" class="btn btn-secondary ml-4 float-left">Back</a>
        <button class="btn btn-secondary ml-2 d-print-none" onclick="window.print()">Print</button>
        <a href="{{route('back.report_generate',$patient->id)}}" class="btn btn-success mr-4 float-right">Finished</a>
    </div>
    <div class="container-fluid report">
        <section class="header">
            <div class="row">
                <div class="col-md-2">
                    <img class="logo-section float-left"
                         src="{{$settings?asset('assets/images/setting/'.$settings->image_logo):''}}">
                </div>
                <div class="col-md-8 text-center text-uppercase">
                    <h4 class="font-weight-bold mt-4">{{$settings->name??''}}</h4>
                    <span>
                        {{$settings->address_area??''}} , {{$settings->address_district??''}}
                    </span>
                    <br>
                    <p>
                        <small>Ph. {{$settings->phone_1??''}} , {{$settings->phone_2??''}}</small>
                        <br>
                    </p>

                    <h6 class="font-weight-bold"><u>Lab Investigation Report</u></h6>
                </div>
            </div>
            <div class="bar-codes" style="margin-bottom: 40px">
                <span class="float-left">
                    {!! \Milon\Barcode\Facades\DNS1DFacade::getBarcodeHTML($patient->his_no,'C128',2.3,33) !!}
                </span>
                <span class="float-right">
                    {!! \Milon\Barcode\Facades\DNS1DFacade::getBarcodeHTML($patient->his_no,'C128',2.3,33) !!}
                </span>
            </div>
        </section>
        <hr>
        <!-- Patient Info Details -->
        <section class="patient-details">
            <div class="row">
                <div class="col-7 text-left">
                    <div class="row">
                        <div class="col-4">
                            <p class="text-uppercase font-weight-bold">
                                HIS NO.<br>
                                Patient Name<br>
                                Category <br>
                                Age/Gender <br>
                                Referred by <br>
                            </p>
                        </div>
                        <div class="col-8">
                            <p class="text-uppercase">
                                : {{$patient->his_no}} <br>
                                : {{$patient->getFullNameAttribute()}}<br>
                                : {{$patient->patient_category}}<br>
                                : {{$patient->age}} Y / {{$patient->gender}}<br>
                                : {{$patient->consultant}} <br>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-5">
                    <div class="row">
                        <div class="col-6">
                            <p class="text-uppercase font-weight-bold">
                                Sample No. <br>
                                Sampe collected <br>
                                Report Authorised <br>
                                BS Date <br>
                            </p>
                        </div>
                        <div class="col-6">
                            <p class="text-uppercase">
                                : {{$patient->samples[0]['sample_code']}}<br>
                                : {{$patient->samples[0]['created_at']}} <br>
                                : {{$patient->reports[0]['created_at']}} <br>
                                : 19/03/2076 <br>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- Test Name and Results Table -->
        <section class="test-results-title">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead class="text-center">
                    <th class="test-name">Test Name</th>
                    <th class="test-result">Result</th>
                    <th class="test-units">units</th>
                    <th style="width: 4% ;">Flag</th>
                    <th class="test-reference">Reference Range</th>
                    </thead>
                </table>
                @php($previous_test_id = 0)
                @php($previous_parent_id = 0)
                @foreach($reports as $r)
                    <table class="table test-results-table">
                        @if($r->testLists->test_id != $previous_test_id)
                            @if(!$loop->first)
                                <br>
                            @endif
                            <h6 class="text-center font-weight-bold text-uppercase">{{$r->testLists->test->name}}</h6>
                        @endif
                        @php($previous_test_id = $r->testLists->test_id)
                        <tbody class="text-center">
                        @if($r->testLists->parent && $r->testLists->parent->id != $previous_parent_id)
                            <tr>
                                <td class="test-name text-uppercase">{{$r->testLists->parent->name}}
                                    ({{$r->testLists->parent->description}})
                                </td>
                                <td class="test-result text-center">{{\App\Models\Report::where('test_list_id',$r->testLists->parent->id)->value('test_list_value')}}</td>
                                <td class="test-units text-center">{{$r->testLists->parent->unit}}</td>
                                <td class="test-flag text-center"></td>
                                <td>{{unserialize($r->testLists->parent->ref_range)}}</td>
                            </tr>
                            @php($previous_parent_id = $r->testLists->parent->id)
                        @endif
                        <tr>
                            <td class="test-name text-capitalize">{{$r->testLists->name}}</td>
                            <td class="test-result">{{$r->test_list_value}}</td>
                            <td class="test-units">{{$r->testLists->unit}}</td>
                            <td class="test-flag"></td>
                            <td>{{unserialize($r->testLists->ref_range)}}</td>
                        </tr>
                        </tbody>
                    </table>
                @endforeach

            </div>
        </section>
        <hr style="border-color: #000;">
        <br>
        <!-- Signatures and printed date -->
        <section class="signature-section">
            <div class="signature">
                <hr style="width: 80%;">
                <h6 class="font-weight-bold text-uppercase">{{$admin->full_name}}</h6>
                <span>Med. Lab Technologist (Lab In charge)</span>
                <br>
            </div>
            <br>
            <p class="ml-4">

                Print Date & Time : {{$date_time->isoFormat('D-M-Y h:mm:ss a')}}
            </p>
        </section>
        <div style="margin-top: 300px;" class="text-center">
            <p>------ End of the Report -----</p>
        </div>
    </div>
@stop
@section('script')
@stop

resources/views/pages/report/view_to_generate_report.blade.php
@extends('master')
@section('content')

    <!-- Begin Page Content -->
    <div class="container-fluid">
        @include('messages.message')
        <div class="card mb-4">
            <div class="card-header col-md-12 card-head">
                <h3 class="m-0 font-weight-bold text-primary d-inline-block col-md-6 mt-1">Report Lists</h3>
                <form action="" class="d-inline-block col-md-6 float-right">
                    <input type="text" class="form-control col-md-10 d-inline-block search-input" name="search"
                           value="{{request()->search}}">
                    <button class="btn btn-primary d-inline-block"><span class="fa fa-search"></span></button>
                </form>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered view-table" id="dataTable" width="100%" cellspacing="0">
                        <thead class="text-center">
                        <tr>
                            <th>SN</th>
                            <th>Full Name</th>
                            <th>Age</th>
                            <th>Gender</th>
                            <th>Sample Code</th>
                            <th>Status</th>
                            <th width="15%">Action</th>
                        </tr>
                        </thead>
                        <tbody class="text-center">
                        @foreach($reports->unique('patient_id') as $report)
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>{{$report->patient->getFullNameAttribute()}}</td>
                                <td>{{$report->patient->age}}</td>
                                <td>{{$report->patient->gender}}</td>
                                <td>{{$report->patient->samples[0]['sample_code']}}</td>
                                <td>{{ucfirst($report->status)}}</td>
                                <td>
                                    @if($report->status == null)
                                        <a href="{{route('report.edit',$report->id)}}" class="btn btn-sm btn-secondary"><i
                                                class="fa fa-edit"></i>
                                        </a>
                                        <a href="{{route('report.show',$report->patient->id)}}"
                                           class="btn btn-sm btn-secondary">Generate&nbsp;<i
                                                class="fa fa-arrow-alt-circle-right"></i>
                                        </a>
                                    @else
                                        <span class="text-uppercase text-danger">Finished</span>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    <div class="float-right">
                        {{$reports->links()}}
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@stop