routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', 'Front\HomeController@homepage');

Route::group(['namespace' => 'Back'], function () {
    Route::get('/login', 'HomeController@login')->name('login')->middleware('guest:admin');
    Route::group(['namespace' => 'Auth'], function () {
        Route::post('login-action', 'LoginController@login')->name('login_action')->middleware('guest:admin');
        Route::get('logout', 'LoginController@logout')->name('logout');
    });

    Route::group(['middleware' => 'auth:admin,SA,RT,LT'], function () {
        Route::get('/dashboard', 'DashboardController@index')->name('index');
        Route::resource('profile', 'ProfileController');
        Route::get('reset-password', 'PasswordResetController@showReset')->name('back.show_reset');
        Route::post('reset-password-action', 'PasswordResetController@resetAction')->name('back.reset_action');
    });

    Route::group(['middleware' => 'auth:admin,SA'], function () {
        Route::resource('admin', 'AdminController');
        Route::get('update-status/{id}', 'AdminController@updateStatus')->name('admin.update_status');
        Route::resource('settings', 'SettingController');
    });

    Route::group(['middleware' => 'auth:admin,SA,RT',], function () {
        Route::resource('patient', 'PatientController', ['excepts' => 'create']);
        Route::get('patient/create/{id?}', ['as' => 'patient.create', 'uses' => 'PatientController@create']);
        Route::get('patient/details/{id}', ['as' => 'patient.details', 'uses' => 'PatientController@patientDetails']);
        Route::get('view-generate-invoice', 'InvoiceController@viewToGenerateInvoice')->name('back.view_to_generate_invoice');
        Route::get('generate-invoice/{id}', 'InvoiceController@generate')->name('back.generate_invoice');
        Route::get('invoice-paid/{id}','InvoiceController@paid')->name('back.invoice_paid');

    });

    Route::group(['middleware' => 'auth:admin,SA,LT',], function () {
        Route::resource('test', 'TestController');
        Route::resource('test-list', 'TestListController');
        Route::get('view-sample', 'SampleController@viewSample')->name('back.view_sample');
        Route::get('collect-sample/{id}', 'SampleController@collect')->name('back.collect_sample');
        Route::post('collect-sample', 'SampleController@collectAction')->name('back.collect_action');
        Route::get('edit-sample/{id}', 'SampleController@editSample')->name('back.edit_sample');
        Route::post('update-sample', 'SampleController@updateSample')->name('back.update_sample');
        Route::get('view-details/{id}', 'SampleController@viewDetails')->name('back.view_details');
        Route::resource('report', 'ReportController', ['excepts' => 'create']);
        Route::get('report/create/{id}', ['as' => 'report.create', 'uses' => 'ReportController@create']);
        Route::get('report/generate/{id}','ReportController@generate')->name('back.report_generate');
    });
});

resources/views/pages/admin/create_admin.blade.php
@extends('master')
@section('content')
    <!-- Begin Page Content -->
    <div class="container">
        <div class="card">
            <div class="card-header text-center text-primary">
                <h4 class="mb-0">Create Admin/Staffs</h4>
            </div>
            <div class="card-body">
                <form action="{{route('admin.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="row col-md-12">
                        <div class="form-group col-md-4">
                            <label for="">Full Name</label>
                            <input type="text" class="form-control" name="full_name" value="{{old('full_name')}}">
                            @error('full_name')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="">User Name</label>
                            <input type="text" class="form-control" name="username" value="{{old('username')}}">
                            @error('username')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="">Email</label>
                            <input type="email" class="form-control" name="email" value="{{old('email')}}">
                            @error('email')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                    </div>
                    <div class="row col-md-12">
                        <div class="form-group col-md-4">
                            <label for="">Address</label>
                            <input type="text" class="form-control" name="address" value="{{old('address')}}">
                            @error('address')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="">Phone</label>
                            <input type="text" class="form-control" name="phone" value="{{old('phone')}}">
                            @error('phone')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="">Gender</label><br>
                            <input type="radio" name="gender" value="M" id="male" {{old('gender') == 'M'?'checked':''}}>&nbsp;<label for="male">Male</label>&nbsp;
                            <input type="radio" name="gender" value="F" id="female" {{old('gender') == 'F'?'checked':''}}>&nbsp;<label
                                for="female">Female</label>&nbsp;
                            <input type="radio" name="gender" value="O" id="others" {{old('gender') == 'O'?'checked':''}}>&nbsp;<label
                                for="others">Others</label>
                            @error('gender')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                    </div>
                    <div class="row col-md-12">
                        <div class="form-group col-md-4">
                            <label for="">Role</label>
                            <select name="role" id="" class="form-control">
                                <option value="" selected disabled>Select Role</option>
                                <option value="SA" {{old('role') == 'SA'?'selected':''}}>Admin</option>
                                <option value="RT" {{old('role') == 'RT'?'selected':''}}>Reception</option>
                                <option value="LT" {{old('role') == 'LT'?'selected':''}}>Lab Technician</option>
                            </select>
                            @error('role')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="from-group col-md-4">
                            <label for="">Image</label>
                            <input type="file" class="form-control-file" name="image">
                        </div>
                    </div>
                    <div class="row col-md-12">
                        <div class="form-group col-md-4">
                            <label for="">Password</label>
                            <input type="password" name="password" class="form-control">
                            @error('password')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="">Confirm Password</label>
                            <input type="password" name="password_confirmation" class="form-control">
                        </div>
                    </div>

                    <div class="text-center mt-2">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@stop

resources/views/pages/admin/edit_admin.blade.php
@extends('master')
@section('content')
    <!-- Begin Page Content -->
    <div class="container">
        <div class="card">
            <div class="card-header text-center text-primary">
                <h4 class="mb-0">Edit Admin/Staffs</h4>
            </div>
            <div class="card-body">
                <form action="{{route('admin.update', $admin->id)}}" method="post" enctype="multipart/form-data">
                    @method('PUT')
                    @csrf
                    <div class="row col-md-12">
                        <div class="form-group col-md-4">
                            <label for="">Full Name</label>
                            <input type="text" class="form-control" name="full_name" value="{{$admin->full_name}}">
                            @error('full_name')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="">User Name</label>
                            <input type="text" class="form-control" name="username" value="{{$admin->username}}">
                            @error('username')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="">Email</label>
                            <input type="email" class="form-control" name="email" value="{{$admin->email}}">
                            @error('email')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                    </div>
                    <div class="row col-md-12">
                        <div class="form-group col-md-4">
                            <label for="">Address</label>
                            <input type="text" class="form-control" name="address" value="{{$admin->address}}">
                            @error('address')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="">Phone</label>
                            <input type="text" class="form-control" name="phone" value="{{$admin->phone}}">
                            @error('phone')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="">Gender</label><br>
                            <input type="radio" name="gender" value="M" id="male" {{$admin->gender == 'M'?'checked':''}}>&nbsp;<label
                                for="male">Male</label>&nbsp;
                            <input type="radio" name="gender" value="F" id="female" {{$admin->gender == 'F'?'checked':''}}>&nbsp;<label
                                for="female">Female</label>&nbsp;
                            <input type="radio" name="gender" value="O" id="others" {{$admin->gender == 'O'?'checked':''}}>&nbsp;<label
                                for="others">Others</label>
                            @error('gender')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                    </div>
                    <div class="row col-md-12">
                        <div class="form-group col-md-4">
                            <label for="">Role</label>
                            <select name="role" id="" class="form-control">
                                <option value="" selected disabled>Select Role</option>
                                <option value="SA" {{$admin->role == 'SA'?'selected':''}}>Admin</option>
                                <option value="RT" {{$admin->role == 'RT'?'selected':''}}>Reception</option>
                                <option value="LT" {{$admin->role == 'LT'?'selected':''}}>Lab Technician</option>
                            </select>
                            @error('role')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="from-group col-md-4">
                            <label for="">Image</label>
                            <input type="file" class="form-control-file" name="image">
                        </div>
                    </div>

                    <div class="text-center mt-2">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@stop

resources/views/pages/admin/view_admins.blade.php
@extends('master')
@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">
        @include('messages.message')
        <div class="card  mb-4">
            <div class="card-header py-3 text-center">
                <h6 class="m-0 font-weight-bold text-primary">Admin / Staffs</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead class="text-center">
                        <tr>
                            <th>SN</th>
                            <th>Full Name</th>
                            <th>Username</th>
                            <th>Email</th>
                            <th>Address</th>
                            <th>Phone</th>
                            <th>Gender</th>
                            <th>Role</th>
                            <th>Status</th>
                            <th width="11%">Action</th>
                        </tr>
                        </thead>
                        <tbody class="text-center">
                        @foreach($admins as $admin)
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>{{$admin->full_name}}</td>
                                <td>{{$admin->username}}</td>
                                <td>{{$admin->email}}</td>
                                <td>{{$admin->address}}</td>
                                <td>{{$admin->phone}}</td>
                                <td>{{$admin->gender}}</td>
                                <td>
                                    @if($admin->role == 'RT')
                                        Reception
                                    @elseif($admin->role == 'LT')
                                        Lab Technician
                                    @else
                                        Admin
                                    @endif
                                </td>
                                <td>
                                    @if($admin->status == 1)
                                        <a href="{{route('admin.update_status', $admin->id)}}"
                                           class="btn btn-sm btn-success"><span class="fa fa-check"></span></a>
                                    @else
                                        <a href="{{route('admin.update_status', $admin->id)}}"
                                           class="btn btn-sm btn-danger"><span class="fa fa-times"></span></a>
                                    @endif
                                </td>
                                <td>
                                    <a href="{{route('admin.edit',$admin->id)}}" class="btn btn-sm btn-secondary mb-1"><span
                                            class="fa fa-edit"></span></a>
                                    <form action="{{route('admin.destroy', $admin->id)}}" method="post" class="form-check-inline">
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit" class="btn btn-sm btn-danger" onclick="return(confirm('Are you sure??'))"><span
                                                class="fa fa-trash"></span>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@stop