routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', 'Front\HomeController@homepage');

Route::group(['namespace' => 'Back'], function () {
    Route::get('/login', 'HomeController@login')->name('login')->middleware('guest:admin');
    Route::group(['namespace' => 'Auth'], function () {
        Route::post('login-action', 'LoginController@login')->name('login_action')->middleware('guest:admin');
        Route::get('logout', 'LoginController@logout')->name('logout');
    });

    Route::group(['middleware' => 'auth:admin,SA,RT,LT'], function () {
        Route::get('/dashboard', 'DashboardController@index')->name('index');
        Route::resource('profile', 'ProfileController');
        Route::get('reset-password', 'PasswordResetController@showReset')->name('back.show_reset');
        Route::post('reset-password-action', 'PasswordResetController@resetAction')->name('back.reset_action');
    });

    Route::group(['middleware' => 'auth:admin,SA'], function () {
        Route::resource('admin', 'AdminController');
        Route::get('update-status/{id}', 'AdminController@updateStatus')->name('admin.update_status');
        Route::resource('settings', 'SettingController');
    });

    Route::group(['middleware' => 'auth:admin,SA,RT',], function () {
        Route::resource('patient', 'PatientController', ['excepts' => 'create']);
        Route::get('patient/create/{id?}', ['as' => 'patient.create', 'uses' => 'PatientController@create']);
        Route::get('patient/details/{id}', ['as' => 'patient.details', 'uses' => 'PatientController@patientDetails']);
        Route::get('view-generate-invoice', 'InvoiceController@viewToGenerateInvoice')->name('back.view_to_generate_invoice');
        Route::get('generate-invoice/{id}', 'InvoiceController@generate')->name('back.generate_invoice');
        Route::get('invoice-paid/{id}','InvoiceController@paid')->name('back.invoice_paid');

    });

    Route::group(['middleware' => 'auth:admin,SA,LT',], function () {
        Route::resource('test', 'TestController');
        Route::resource('test-list', 'TestListController');
        Route::get('view-sample', 'SampleController@viewSample')->name('back.view_sample');
        Route::get('collect-sample/{id}', 'SampleController@collect')->name('back.collect_sample');
        Route::post('collect-sample', 'SampleController@collectAction')->name('back.collect_action');
        Route::get('edit-sample/{id}', 'SampleController@editSample')->name('back.edit_sample');
        Route::post('update-sample', 'SampleController@updateSample')->name('back.update_sample');
        Route::get('view-details/{id}', 'SampleController@viewDetails')->name('back.view_details');
        Route::resource('report', 'ReportController', ['excepts' => 'create']);
        Route::get('report/create/{id}', ['as' => 'report.create', 'uses' => 'ReportController@create']);
        Route::get('report/generate/{id}','ReportController@generate')->name('back.report_generate');
    });
});

app/Models/Patient.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Patient extends Model
{
    protected $table = 'patients';
    protected $fillable = ['first_name', 'middle_name', 'last_name', 'age', 'email', 'gender', 'address', 'phone', 'consultant', 'patient_category', 'his_no'];

    public function samples()
    {
        return $this->hasMany(Sample::class);
    }

    public function testLists()
    {
        return $this->belongsToMany(TestList::class, 'samples');
    }

    public function sampleType()
    {
        return $this->hasMany(SampleType::class);
    }

    public function getFullNameAttribute()
    {
        return ucwords($this->first_name . ' ' . $this->middle_name . ' ' . $this->last_name);
    }

    public function reports()
    {
        return $this->hasMany(Report::class, 'patient_id');
    }

    public function invoice()
    {
        return $this->hasOne(Invoice::class);
    }

}

app/Http/Controllers/Back/PatientController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Http\Controllers\DateConverterController;
use App\Http\Requests\PatientStoreRequest;
use App\Models\Invoice;
use App\Models\Patient;
use App\Models\Sample;
use App\Models\SampleType;
use App\Models\TestList;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Mockery\Exception;
use function PHPSTORM_META\type;

class PatientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $patients = Patient::query();
        if (\request()->has('search')) {
            $search_key = \request()->input('search');
            $patients->where('first_name', 'like', '%' . $search_key . '%')
                ->orWhere('phone', 'like', '%' . $search_key . '%')
                ->orWhere('his_no', 'like', '%' . $search_key . '%');
        }
        $patients = $patients->latest()->paginate(20);
        return view('pages.patient.view_patients', compact('patients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $patient = null;
        $test_lists = TestList::where('parent_id', null)->get();
//        foreach ($test_lists as $tl){
//            dd($tl);
//        }
//        dd($test_lists);
        if (\request()->id) {
            $patient = Patient::where('id', \request()->id)->first();
//            dd($patient->testLists);
            return view('pages.patient.create_patient', compact('test_lists', 'patient'));
        }
        return view('pages.patient.create_patient', compact('test_lists', 'patient'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(PatientStoreRequest $request)
    {

        if ($request->input('old_patient') == null) {
            //================== create new patient =================//
            $patient = new Patient();
            $patient->first_name = $request->input('first_name');
            $patient->middle_name = $request->input('middle_name');
            $patient->last_name = $request->input('last_name');
            $patient->address = $request->input('address');
            $patient->phone = $request->input('phone');
            $patient->email = $request->input('email');
            $patient->gender = $request->input('gender');
            $patient->age = $request->input('age');
            $patient->consultant = $request->input('consultant');
            $patient->patient_category = $request->input('patient_category');
            $patient->save();
        } else {
            //====================== Old Patient ============================//
            $patient = Patient::findOrFail($request->input('old_patient'));
            $patient->first_name = $request->input('first_name');
            $patient->middle_name = $request->input('middle_name');
            $patient->last_name = $request->input('last_name');
            $patient->address = $request->input('address');
            $patient->phone = $request->input('phone');
            $patient->email = $request->input('email');
            $patient->gender = $request->input('gender');
            $patient->age = $request->input('age');
            $patient->consultant = $request->input('consultant');
            $patient->patient_category = $request->input('patient_category');
            $patient->status = null;
            $patient->save();
        }

        //================== create sample of specific patient =====================//
        $tests = $request->input('tests');
        $test_list_id = [];
        $sample_code = mt_rand(10000000, 99999999);
        foreach ($tests as $test) {
            array_push($test_list_id, $test);
            $sample = new Sample();
            $sample->patient_id = $patient->id;
            $sample->test_list_id = $test;
            $sample->sample_code = $sample_code;
            $sample->save();
        }

        //================ create invoice of specific patient ============================//
        $invoice = new Invoice();
        $invoice->patient_id = $patient->id;

        $convert_date = new  DateConverterController();
        $date_time = Carbon::now('+5:45');
        $bs_date = ($convert_date->eng_to_nep($date_time->year, $date_time->month, $date_time->day));
        $year_now = $bs_date['year'] % 100;
        $year_next = ($bs_date['year'] + 1) % 100;
        $rand_no = mt_rand(10000, 99999);
        $inv_no = $year_now . '-' . $year_next . '/' . $bs_date['month'] . '/' . $rand_no;
        $invoice->inv_no = $inv_no;
        $total_amount = 0;
        foreach ($test_list_id as $tld) {
            $single_cost = TestList::where('id', $tld)->value('cost');
            $total_amount += $single_cost;
        }
        $invoice->total_amount = $total_amount;
        $invoice->save();
        return redirect()->route('back.view_to_generate_invoice');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $test_lists = TestList::where('parent_id', null)->get();
        $patient = Patient::findOrFail($id);
        return view('pages.patient.edit_patient', compact('patient', 'test_lists'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $patient = Patient::findOrFail($id);
        $invoice_status = Invoice::where('patient_id', $patient->id)->value('status');
        $sample = Sample::where('patient_id', $patient->id)->first();

        if ($invoice_status == 'unpaid' && $sample->status == 'pending') {

            $patient->first_name = $request->input('first_name');
            $patient->middle_name = $request->input('middle_name');
            $patient->last_name = $request->input('last_name');
            $patient->address = $request->input('address');
            $patient->phone = $request->input('phone');
            $patient->email = $request->input('email');
            $patient->gender = $request->input('gender');
            $patient->age = $request->input('age');
            $patient->consultant = $request->input('consultant');
            $patient->patient_category = $request->input('patient_category');
            $patient->save();


            //================== update sample of specific patient =====================//
            $tests = $request->input('tests');
            $test_list_id = [];
            $sample_code = mt_rand(10000000, 99999999);
            foreach ($patient->samples as $sample) {
                $sample->delete();
            }
            foreach ($tests as $test) {
                array_push($test_list_id, $test);
                $sample = new Sample();
                $sample->patient_id = $patient->id;
                $sample->test_list_id = $test;
                $sample->sample_code = $sample_code;
                $sample->save();
            }

            //================ create invoice of specific patient ============================//
            $invoice = Invoice::where('patient_id', $patient->id)->first();
            $total_amount = 0;
            foreach ($test_list_id as $tld) {
                $single_cost = TestList::where('id', $tld)->value('cost');
                $total_amount += $single_cost;
            }
            $invoice->total_amount = $total_amount;
            $invoice->save();

            return redirect()->route('patient.index')->with('success', 'Patient updated successfully');

        } else {
            $patient->first_name = $request->input('first_name');
            $patient->middle_name = $request->input('middle_name');
            $patient->last_name = $request->input('last_name');
            $patient->address = $request->input('address');
            $patient->phone = $request->input('phone');
            $patient->email = $request->input('email');
            $patient->gender = $request->input('gender');
            $patient->age = $request->input('age');
            $patient->consultant = $request->input('consultant');
            $patient->patient_category = $request->input('patient_category');
            $patient->save();
            return redirect()->route('patient.index')->with('success', 'Can only update patient details');
        }
    }


    /**
     * Show old patient's details with their respective tests and reports
     */
    public function patientDetails()
    {
        $patient_id = \request()->id;
        $patient = Patient::where('id', \request()->id)->first();
        return view('pages.patient.view_patient_details', compact('patient'));
    }


    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $patient = Patient::findOrFail($id);
        try {
            $patient->delete();
            return redirect()->back()->with('success', 'Patient deleted successfully');
        } catch (\Exception $e) {
            return redirect()->back()->with('fail', 'Cannot delete patient');
        }
    }
}

resources/views/pages/patient/create_patient.blade.php
@extends('master')
@section('content')
    <!-- Begin Page Content -->
    <div class="container">
        <div class="card">
            <div class="card-header text-center">
                <h4 class="mb-0 text-primary text-bold">Create Patient</h4>
            </div>
            <div class="card-body">
                <form action="{{route('patient.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" value="{{$patient?$patient->id:null}}" name="old_patient">
                    <div class="row col-md-12">
                        <div class="form-group col-md-4">
                            <label for="">First Name</label>
                            <input type="text" class="form-control" name="first_name"
                                   value="{{$patient?$patient->first_name:old('first_name')}}" placeholder="eg. Purna">
                            @error('first_name')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="">Middle Name</label>
                            <input type="text" class="form-control" name="middle_name"
                                   value="{{$patient?$patient->middle_name:old('middle_name')}}"
                                   placeholder="eg. Bahadur">
                            @error('middle_name')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="">Last Name</label>
                            <input type="text" class="form-control" name="last_name"
                                   value="{{$patient?$patient->last_name:old('last_name')}}" placeholder="eg. Magar">
                            @error('last_name')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                    </div>
                    <div class="row col-md-12">
                        <div class="form-group col-md-4">
                            <label for="">Email</label>
                            <input type="email" class="form-control" name="email"
                                   value="{{$patient?$patient->email:old('email')}}"
                                   placeholder="eg. example@gmail.com">
                            @error('email')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="">Address</label>
                            <input type="text" class="form-control" name="address"
                                   value="{{$patient?$patient->address:old('address')}}"
                                   placeholder="eg. Baneshowr -12 , Kathmandu">
                            @error('address')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="">Phone</label>
                            <input type="text" class="form-control" name="phone"
                                   value="{{$patient?$patient->phone:old('phone')}}" placeholder="eg. 9876383748">
                            @error('phone')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                    </div>

                    <div class="row col-md-12">
                        <div class="form-group col-md-4">
                            <label for="">Gender</label><br>
                            <input type="radio" name="gender" value="M"
                                   id="male" @if($patient){{$patient->gender == 'M'?'checked':''}}@else {{old('gender') == 'M'?'checked':''}} @endif>&nbsp;<label
                                for="male">Male</label>&nbsp;
                            <input type="radio" name="gender" value="F"
                                   id="female" @if($patient){{$patient->gender == 'F'?'checked':''}}@else {{old('gender') == 'F'?'checked':''}} @endif>&nbsp;<label
                                for="female">Female</label>&nbsp;
                            <input type="radio" name="gender" value="O"
                                   id="others" @if($patient){{$patient->gender == 'O'?'checked':''}}@else {{old('gender') == 'O'?'checked':''}} @endif>&nbsp;<label
                                for="others">Others</label>
                            @error('gender')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="">Age</label>
                            <input type="number" class="form-control" name="age" placeholder="eg. 30" max="120" min="1"
                                   value="{{$patient?$patient->age:old('age')}}">
                            @error('age')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                    </div>

                    <div class="row col-md-12">
                        <div class="form-group col-md-6">
                            <label for="">Consultant</label>
                            <input type="text" class="form-control" name="consultant" placeholder="eg. Dr. John Snow"
                                   value="{{$patient?$patient->consultant:old('consultant')}}">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="">Patient Category</label>
                            <select name="patient_category" id="" class="form-control">
                                <option value="" selected disabled>Select Patient Category</option>
                                <option
                                    value="general" @if($patient && $patient->patient_category == 'general'){{'selected'}} @elseif(old('general')== 'general') {{'selected'}}@endif>
                                    General
                                </option>
                            </select>
                        </div>
                    </div>
                    <div class="row col-md-12">
                        <div class="form-group col-md-6">
                            <label for="">Test List</label>
                            <select name="tests[]" id="" class="form-control select-tests" multiple="multiple">
                                @foreach($test_lists as $tl)
                                    <option
                                        value="{{$tl->id}}"
                                    @if($patient)
                                        @foreach($patient->testLists as $ptl)
                                            {{$ptl->test_id == $tl->test_id?'selected':''}}
                                            @endforeach
                                        @else
                                        {{collect(old('tests'))->contains($tl->id)?'selected':''}}
                                        @endif>{{$tl->name}}
                                    </option>
                                @endforeach
                            </select>
                            @error('tests')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                    </div>

                    <div class="text-center mt-2 mb-4">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
@stop
@section('script')
    <script>
        $(document).ready(function () {
            $('.select-tests').select2({
                placeholder: 'Select Tests',
                theme: 'classic',
            });
        });
    </script>
@stop

resources/views/pages/patient/view_patients.blade.php
@extends('master')
@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">
        @include('messages.message')
        <div class="card">
            <div class="card-header col-md-12 card-head">
                <h3 class="m-0 font-weight-bold text-primary d-inline-block col-md-6 mt-1">Patient Lists</h3>
                <form action="" class="float-right col-md-6">
                    <input type="text" class="form-control d-inline col-md-10 search-input" placeholder="search patient"
                           value="{{request()->search}}" name="search">
                    <button class="btn btn-primary ml-1"><span class="fa fa-search"></span></button>
                </form>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered view-table" id="dataTable" width="100%" cellspacing="0">
                        <thead class="text-center">
                        <tr>
                            <th>SN</th>
                            <th>His_no</th>
                            <th>Full Name</th>
                            <th>Address</th>
                            <th>Phone</th>
                            <th>Gender</th>
                            <th>Age</th>
                            <th width="11%">Action</th>
                        </tr>
                        </thead>
                        <tbody class="text-center">
                        @foreach($patients as $patient)
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>{{$patient->his_no}}</td>
                                <td>{{$patient->getFullNameAttribute()}}</td>
                                <td>{{$patient->address}}</td>
                                <td>{{$patient->phone}}</td>
                                <td>{{$patient->gender}}</td>
                                <td>{{$patient->age}}</td>
                                <td>
                                    @if(!$patient->status)
                                        <a href="{{route('patient.edit',$patient->id)}}"
                                           class="btn btn-sm btn-secondary mb-1"><span
                                                class="fa fa-edit"></span></a>
                                        <form action="{{route('patient.destroy', $patient->id)}}" method="post"
                                              class="form-check-inline">
                                            @method('DELETE')
                                            @csrf
                                            <button type="submit" class="btn btn-sm btn-danger"
                                                    onclick="return(confirm('Are you Sure??'))"><span
                                                    class="fa fa-trash"></span>
                                            </button>
                                        </form>
                                    @endif
                                    @if($patient->status)
                                        <a href="{{route('patient.create',['id'=>$patient->id])}}"
                                           class="btn btn-sm btn-primary mb-1 "><span
                                                class="fa fa-plus-circle"></span></a>
                                        <a href="{{route('patient.details',['id'=>$patient->id])}}"
                                           class="btn btn-sm btn-primary mb-1 mr-2"><span
                                                class="fa fa-eye"></span></a>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="float-right">
                    {{$patients->links()}}
                </div>
            </div>

        </div>

    </div>
    <!-- /.container-fluid -->
@stop