routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', 'Front\HomeController@homepage');

Route::group(['namespace' => 'Back'], function () {
    Route::get('/login', 'HomeController@login')->name('login')->middleware('guest:admin');
    Route::group(['namespace' => 'Auth'], function () {
        Route::post('login-action', 'LoginController@login')->name('login_action')->middleware('guest:admin');
        Route::get('logout', 'LoginController@logout')->name('logout');
    });

    Route::group(['middleware' => 'auth:admin,SA,RT,LT'], function () {
        Route::get('/dashboard', 'DashboardController@index')->name('index');
        Route::resource('profile', 'ProfileController');
        Route::get('reset-password', 'PasswordResetController@showReset')->name('back.show_reset');
        Route::post('reset-password-action', 'PasswordResetController@resetAction')->name('back.reset_action');
    });

    Route::group(['middleware' => 'auth:admin,SA'], function () {
        Route::resource('admin', 'AdminController');
        Route::get('update-status/{id}', 'AdminController@updateStatus')->name('admin.update_status');
        Route::resource('settings', 'SettingController');
    });

    Route::group(['middleware' => 'auth:admin,SA,RT',], function () {
        Route::resource('patient', 'PatientController', ['excepts' => 'create']);
        Route::get('patient/create/{id?}', ['as' => 'patient.create', 'uses' => 'PatientController@create']);
        Route::get('patient/details/{id}', ['as' => 'patient.details', 'uses' => 'PatientController@patientDetails']);
        Route::get('view-generate-invoice', 'InvoiceController@viewToGenerateInvoice')->name('back.view_to_generate_invoice');
        Route::get('generate-invoice/{id}', 'InvoiceController@generate')->name('back.generate_invoice');
        Route::get('invoice-paid/{id}','InvoiceController@paid')->name('back.invoice_paid');

    });

    Route::group(['middleware' => 'auth:admin,SA,LT',], function () {
        Route::resource('test', 'TestController');
        Route::resource('test-list', 'TestListController');
        Route::get('view-sample', 'SampleController@viewSample')->name('back.view_sample');
        Route::get('collect-sample/{id}', 'SampleController@collect')->name('back.collect_sample');
        Route::post('collect-sample', 'SampleController@collectAction')->name('back.collect_action');
        Route::get('edit-sample/{id}', 'SampleController@editSample')->name('back.edit_sample');
        Route::post('update-sample', 'SampleController@updateSample')->name('back.update_sample');
        Route::get('view-details/{id}', 'SampleController@viewDetails')->name('back.view_details');
        Route::resource('report', 'ReportController', ['excepts' => 'create']);
        Route::get('report/create/{id}', ['as' => 'report.create', 'uses' => 'ReportController@create']);
        Route::get('report/generate/{id}','ReportController@generate')->name('back.report_generate');
    });
});

app/Models/TestList.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use phpDocumentor\Reflection\Types\Self_;

class TestList extends Model
{
    protected $table = 'test_lists';
    protected $fillable = ['test_id', 'parent_id', 'name', 'unit', 'normal', 'abnormal', 'ref_range', 'description', 'cost'];

    public function test()
    {
        return $this->belongsTo(Test::class, 'test_id');
    }

    public function subCategories()
    {
        return $this->hasMany(TestList::class, 'parent_id');
    }

    public function parent()
    {
        return $this->belongsTo(TestList::class);
    }

    public function reports()
    {
        return $this->hasMany(Report::class);
    }

    public function samples()
    {
        return $this->belongsTo(Sample::class);
    }

}

app/Http/Controllers/Back/TestListController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Test;
use App\Models\TestList;
use Illuminate\Http\Request;

class TestListController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $test_lists = TestList::all();
        return view('pages.test_list.view_test_lists', compact('test_lists'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $test_categories = Test::all();
        $test_lists = TestList::where('parent_id', null)->get();
        return view('pages.test_list.create_test_list', compact('test_categories', 'test_lists'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'test_list_name' => 'required',
            'test_category' => 'required',
        ]);

        $test_list = new TestList();
        $test_list->test_id = $request->input('test_category');
        $test_list->name = $request->input('test_list_name');
        $test_list->unit = $request->input('unit');
        $test_list->cost = $request->input('cost');
        $test_list->ref_range = serialize($request->input('ref_range'));
        $test_list->normal = $request->input('normal');
        $test_list->abnormal = $request->input('abnormal');
        $test_list->description = $request->input('description');
        if ($request->has('test_list_id') && $request->test_list_id != null) {
            $test_list->parent_id = $request->input('test_list_id');
        }
        if ($test_list->save()) {
            return redirect()->route('test-list.index')->with('success', 'Test list successfully created');
        }
        return redirect()->back()->with('fail', 'Something went wrong, Please create again');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $test_categories = Test::all();
        $test_lists = TestList::all();
        $test_list = TestList::findOrFail($id);
        return view('pages.test_list.edit_test_list', compact('test_list', 'test_categories', 'test_lists'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $test_list = TestList::findOrFail($id);
        $this->validate($request, [
            'test_list_name' => 'required',
            'test_category' => 'required',

        ]);

        $test_list->test_id = $request->input('test_category');
        $test_list->name = $request->input('test_list_name');
        $test_list->unit = $request->input('unit');
        $test_list->cost = $request->input('cost');
        $test_list->ref_range = serialize($request->input('ref_range'));
        $test_list->normal = $request->input('normal');
        $test_list->abnormal = $request->input('abnormal');
        $test_list->description = $request->input('description');


        if ($request->has('test_list_id') && $request->test_list_id != null) {
            $test_list->parent_id = $request->input('test_list_id');
        } else {
            $test_list->parent_id = null;
        }

        if ($test_list->save()) {
            return redirect()->route('test-list.index')->with('success', 'Test List successfully updated');
        }
        return redirect()->route('test-list.index')->with('success', 'Something went wrong');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $test_list = TestList::findOrFail($id);
        try {
            $test_list->delete();
            return redirect()->back()->with('success', 'Test list deleted');
        } catch (\Exception $e) {
            return redirect()->back()->with('fail', 'Cannot delete test list');
        }
    }
}

resources/views/pages/test_list/create_test_list.blade.php
@extends('master')
@section('content')
    <!-- Begin Page Content -->
    <div class="container">
        <div class="card">
            <div class="card-header text-center text-primary">
                <h4 class="mb-0">Create Test Lists</h4>
            </div>

            <div class="card-body">
                <form action="{{route('test-list.store')}}" method="post">
                    @csrf
                    <div class="row col-md-12 mb-4">
                        <div class="from-group col-md-6">
                            <label for="">Test Category</label>
                            <select name="test_category" id="" class="form-control test-category">
                                <option value="" selected disabled="">Select test category</option>
                                @foreach($test_categories as $tc)
                                    <option
                                        value="{{$tc->id}}" {{old('test_category') == $tc->id?'selected':''}}>{{$tc->name}}</option>
                                @endforeach
                            </select>
                            @error('test_category')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="from-group col-md-6">
                            <label for="">Test Lists (
                                <small>Select only if Test List has parent category</small>)
                            </label>
                            <select name="test_list_id" class="form-control test-list">
                                <option value="" selected disabled="">Select test category</option>
                                @foreach($test_lists as $tl)
                                    <option
                                        value="{{$tl->id}}" {{old('test_list_id') == $tl->id?'selected':''}}>{{$tl->name}}</option>
                                @endforeach
                            </select>
                            @error('test_list_id')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                    </div>
                    <div class="row col-md-12">
                        <div class="form-group col-md-4">
                            <label for="">Name</label>
                            <input type="text" class="form-control" name="test_list_name"
                                   value="{{old('test_list_name')}}" placeholder="eg. WBC">
                            @error('test_list_name')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="">Unit</label>
                            <input type="text" class="form-control" name="unit" value="{{old('unit')}}"
                                   placeholder="eg. /cmm">
                            @error('unit')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="from-group col-md-4">
                            <label for="">Test Cost</label>
                            <input type="number" class="form-control" name="cost" value="{{old('cost')}}" placeholder="Rs.">
                            @error('cost')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                    </div>
                    <div class="row col-md-12">
                        <div class="form-group col-md-12">
                            <label for="">Description</label>
                            <input type="text" class="form-control" name="description"
                                   value="{{old('description')}}" placeholder="eg. White Blood Cell Count">
                            @error('description')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                    </div>

                    <div class="row col-md-12 mt-4">
                        <div class="form-group col-md-4">
                            <label for="">Reference Range</label>
                            <input type="text" class="form-control" name="ref_range" value="{{old('ref_range')}}"
                                   placeholder="eg. 4000-11000">
                            @error('ref_range')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="">Normal</label>
                            <input type="text" class="form-control" name="normal" value="{{old('normal')}}"
                                   placeholder="eg. 5000">
                            @error('normal')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="">Abnormal</label>
                            <input type="text" class="form-control" name="abnormal" value="{{old('abnormal')}}"
                                   placeholder="eg. 10000">
                            @error('abnormal')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                    </div>
                    <div class="mt-4 text-center">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@stop
@section('script')
    <script>
        $(document).ready(function () {
            $('.test-category').select2({
                placeholder: 'Select Test Category',
                theme:'classic',
            });
            $('.test-list').select2({
                placeholder: 'Select Test Category',
                theme:'classic',

            });
        })
    </script>
@stop

resources/views/pages/test_list/edit_test_list.blade.php
@extends('master')
@section('content')
    <!-- Begin Page Content -->
    <div class="container">
        <div class="card">
            <div class="card-header text-primary text-center">
                <h4 class="mb-0">Edit Test Lists</h4>
            </div>

            <div class="card-body col-md-12">
                <form action="{{route('test-list.update',$test_list->id)}}" method="post">
                    @method('PUT')
                    @csrf

                    <div class="row col-md-12 mb-4">
                        <div class="from-group col-md-6">
                            <label for="">Test Category</label>
                            <select name="test_category" id="" class="form-control">
                                <option value="" selected disabled="">Select test category</option>
                                @foreach($test_categories as $tc)
                                    <option
                                        value="{{$tc->id}}" {{$test_list->test_id == $tc->id?'selected':''}}>{{$tc->name}}</option>
                                @endforeach
                            </select>
                            @error('test_category')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="from-group col-md-6">
                            <label for="">Test Lists (
                                <small>Select only if Test List has parent category</small>
                                ) </label>
                            <select name="test_list_id" id="" class="form-control">
                                <option value="" selected disabled="">Select test category</option>
                                @foreach($test_lists as $tl)
                                    <option
                                        value="{{$tl->id}}" {{$test_list->parent_id == $tl->id?'selected':''}}>{{$tl->name}}</option>
                                @endforeach
                                <option value="">None</option>
                            </select>
                            @error('test_list_id')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                    </div>
                    <div class="row col-md-12">
                        <div class="form-group col-md-4">
                            <label for="">Name</label>
                            <input type="text" class="form-control" name="test_list_name"
                                   value="{{$test_list->name}}">
                            @error('test_list_name')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="">Unit</label>
                            <input type="text" class="form-control" name="unit" value="{{$test_list->unit}}">
                            @error('unit')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>

                        <div class="from-group col-md-4">
                            <label for="">Test Cost</label>
                            <input type="text" class="form-control" name="cost" value="{{$test_list->cost}}">
                            @error('cost')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                    </div>

                    <div class="row col-md-12">
                        <div class="form-group col-md-12">
                            <label for="">Description</label>
                            <input type="text" class="form-control" name="description"
                                   value="{{$test_list->description}}">
                            @error('description')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                    </div>

                    <div class="row col-md-12 mt-4">
                        <div class="form-group col-md-4">
                            <label for="">Reference Range</label>
                            <input type="text" class="form-control" name="ref_range" value="{{unserialize($test_list->ref_range) }}">
                            @error('ref_range')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="">Normal</label>
                            <input type="text" class="form-control" name="normal" value="{{$test_list->normal}}">
                            @error('normal')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="">Abnormal</label>
                            <input type="text" class="form-control" name="abnormal" value="{{$test_list->abnormal}}">
                            @error('abnormal')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>
                    </div>
                    <div class="mt-4 mb-4 text-center">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@stop

resources/views/pages/test_list/view_test_lists.blade.php
@extends('master')
@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">
        @include('messages.message')
        <div class="card mb-4">
            <div class="card-header ">
                <h4 class="m-0 font-weight-bold text-primary">Test Lists
                    <a href="{{route('test-list.create')}}" class="btn btn-sm btn-primary float-right">
                        <li class="fa fa-plus"></li>
                        Create Test List</a></h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered view-table" id="dataTable" width="100%" cellspacing="0">
                        <thead class="text-center">
                        <tr>
                            <th>SN</th>
                            <th>Name</th>
                            <th>Unit</th>
                            <th>Ref Range</th>
                            <th>Normal</th>
                            <th>Abnormal</th>
                            <th>Test Category</th>
                            <th>Cost</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody class="text-center">
                        @foreach($test_lists as $test_list)
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>{{$test_list->name}}</td>
                                <td>{{$test_list->unit}}</td>
                                <td>{{unserialize($test_list->ref_range)}}</td>
                                <td>{{$test_list->normal}}</td>
                                <td>{{$test_list->abnormal}}</td>
                                <td>
                                    {{$test_list->test->name}}
                                    {{$test_list->parent_id?'-':''}}
                                    {{\App\Models\TestList::where('id',$test_list->parent_id)->value('name')}}
                                </td>
                                <td>Rs. {{$test_list->cost}}</td>
                                <td>
                                    <a href="{{route('test-list.edit',$test_list->id)}}"
                                       class="btn btn-sm btn-secondary mb-1"><span
                                            class="fa fa-edit"></span></a>
                                    <form action="{{route('test-list.destroy', $test_list->id)}}" method="post"
                                          class="form-check-inline">
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit" class="btn btn-sm btn-danger"  onclick="return(confirm('Are You Sure'))"><span
                                                class="fa fa-trash"></span>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@stop